node {
       stage 'Step 1: Test'
           build job: 'Verify Apostille/Verify Apostille Test', parameters: [[$class: 'StringParameterValue', name: 'Branch', value: '*/Development']]
        stage 'Step 2: Deploy to Integration'
             build job: 'Service Deployment/Deploy to Integration', parameters: [[$class: 'StringParameterValue', name: 'Repo', value: 'https://github.com/UKForeignOffice/verify-apostille-service.git'], [$class: 'StringParameterValue', name: 'Branch', value: 'Development'], [$class: 'StringParameterValue', name: 'Tag', value: 'verify-apostille-int'], [$class: 'StringParameterValue', name: 'Container', value: 'verify-apostille-service']]
}
